### ISSUE TITLE
How to use the repo without using the OpenAI API

### ISSUE THREAD

**Issue by RayminL** [robot-learning-freiburg/MoMa-LLM#7]
Hello, I don't want to use the API and only test the baseline. 

But I set :
`agent: greedy`
 in `moma_llm.yaml` 
 
 and deleted 
 ```
 "--env",
"OPENAI_ORGANIZATION=todo",
"--env",
"OPENAI_API_KEY=todo",
```
in devcontainer.json, but it still reports an error.
What should I do? Thank you very much.

**Comment by dHonerkamp** [comment]
Hi, that should definitely be possible. What error are you getting if you don't delete the env variables but just set them to a random string?

**Comment by RayminL** [comment]
Hi, this is my error.

```
root@robotics173:/workspaces/MoMa-LLM# python run_agent.py

 _   _____  _  _
(_) / ____|(_)| |
 _ | |  __  _ | |__   ___   ___   _ __
| || | |_ || || '_ \ / __| / _ \ | '_ \
| || |__| || || |_) |\__ \| (_) || | | |
|_| \_____||_||_.__/ |___/ \___/ |_| |_|

Traceback (most recent call last):
  File "run_agent.py", line 26, in <module>
    from moma_llm.env.baselines import (GreedyBaseline,
  File "/workspaces/MoMa-LLM/moma_llm/env/baselines.py", line 13, in <module>
    from moma_llm.env.llm_env import LLMEnv
  File "/workspaces/MoMa-LLM/moma_llm/env/llm_env.py", line 19, in <module>
    from moma_llm.env.env import OurIGibsonEnv
  File "/workspaces/MoMa-LLM/moma_llm/env/env.py", line 24, in <module>
    from moma_llm.tasks.object_search_task import ObjectSearchTask
  File "/workspaces/MoMa-LLM/moma_llm/tasks/object_search_task.py", line 27, in <module>
    from moma_llm.llm.llm import LLM
  File "/workspaces/MoMa-LLM/moma_llm/llm/llm.py", line 27, in <module>
    client = OpenAI(organization=os.environ["OPENAI_ORGANIZATION"], api_key=os.environ["OPENAI_API_KEY"])
  File "/miniconda/envs/igibson/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'OPENAI_ORGANIZATION'
```

**Comment by dHonerkamp** [comment]
Thanks for the error trace.

As mentioned, please don't delete the env variables, but just them to a random string:
```
"OPENAI_ORGANIZATION=asdsd",
"OPENAI_API_KEY=asdsd",
```

Though testing it, you also have to change the following line https://github.com/robot-learning-freiburg/MoMa-LLM/blob/5db816cf4da6217eb55bf75fb14930c467804681/run_agent.py#L48
to `LLM = None`

I'm afraid I don't have a machine with the dataset downloaded right now, but that seemed to initialize everything fine. Let me know in case there is an error afterwards.

**Comment by RayminL** [comment]
Thank you, I have already resolved this issue. I appreciate your response!
